# Generated by Django 2.1.1 on 2018-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtag',
            name='name',
            field=models.CharField(max_length=64, verbose_name='标签名'),
        ),
        migrations.AlterField(
            model_name='blogtag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='标签索引'),
        ),
    ]
