# Generated by Django 2.1.1 on 2018-09-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MySiteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.CharField(max_length=30, verbose_name='网站标题')),
                ('introduction', models.CharField(max_length=64, verbose_name='网站简介')),
                ('source_of_power', models.CharField(max_length=64, verbose_name='网站作者和网站框架')),
                ('approval_number', models.CharField(max_length=64, verbose_name='网站审批号')),
            ],
            options={
                'verbose_name': '网站信息',
                'verbose_name_plural': '网站信息',
                'ordering': ['id'],
            },
        ),
    ]
