# Generated by Django 2.1.1 on 2018-09-26 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toolbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='文章')),
                ('author', models.CharField(default='sing', max_length=50, verbose_name='作者')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('slug', models.SlugField(unique=True, verbose_name='后缀')),
            ],
            options={
                'verbose_name': '关于页面内容',
                'verbose_name_plural': '关于页面内容',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='BookLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='链接名称')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='书籍链接')),
            ],
            options={
                'verbose_name': '书籍',
                'verbose_name_plural': '书籍链接列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FriendLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='链接名称')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
            ],
            options={
                'verbose_name': '友情链接',
                'verbose_name_plural': '友情链接列表',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('body', models.TextField(verbose_name='文章')),
                ('author', models.CharField(default='sing', max_length=50, verbose_name='作者')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('slug', models.SlugField(unique=True, verbose_name='后缀')),
            ],
            options={
                'verbose_name': '公告和首页信息',
                'verbose_name_plural': '公告和首页信息',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='SpaceLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='链接名称')),
                ('link', models.URLField(help_text='请填写http或https开头的完整形式地址', verbose_name='友链地址')),
            ],
            options={
                'verbose_name': '个人链接',
                'verbose_name_plural': '个人空间链接列表',
                'ordering': ['id'],
            },
        ),
    ]
